# Generated by Django 3.1.3 on 2020-11-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('diamd_no', models.CharField(db_column='DIAMD_NO', max_length=9, primary_key=True, serialize=False)),
                ('stock_no', models.CharField(db_column='STOCK_NO', max_length=9)),
                ('parent_item_no_alt', models.CharField(blank=True, db_column='PARENT_ITEM_NO_ALT', max_length=9, null=True)),
                ('bounce_use_item', models.CharField(blank=True, db_column='BOUNCE_USE_ITEM', max_length=9, null=True)),
                ('full_title', models.CharField(db_column='FULL_TITLE', max_length=60)),
                ('main_desc', models.CharField(db_column='MAIN_DESC', max_length=60)),
                ('variant_desc', models.CharField(blank=True, db_column='VARIANT_DESC', max_length=60, null=True)),
                ('series_code', models.IntegerField(db_column='SERIES_CODE')),
                ('issue_no', models.IntegerField(blank=True, db_column='ISSUE_NO', null=True)),
                ('issue_seq_no', models.IntegerField(db_column='ISSUE_SEQ_NO')),
                ('volume_tag', models.CharField(blank=True, db_column='VOLUME_TAG', max_length=9, null=True)),
                ('max_issue', models.IntegerField(blank=True, db_column='MAX_ISSUE', null=True)),
                ('price', models.DecimalField(db_column='PRICE', decimal_places=2, max_digits=10)),
                ('publisher', models.CharField(db_column='PUBLISHER', max_length=9)),
                ('upc_no', models.CharField(blank=True, db_column='UPC_NO', max_length=17, null=True)),
                ('short_isbn_no', models.CharField(blank=True, db_column='SHORT_ISBN_NO', max_length=10, null=True)),
                ('ean_no', models.CharField(blank=True, db_column='EAN_NO', max_length=18, null=True)),
                ('cards_per_pack', models.IntegerField(db_column='CARDS_PER_PACK')),
                ('pack_per_box', models.IntegerField(db_column='PACK_PER_BOX')),
                ('box_per_case', models.IntegerField(db_column='BOX_PER_CASE')),
                ('discount_code', models.CharField(db_column='DISCOUNT_CODE', max_length=2)),
                ('increment', models.IntegerField(db_column='INCREMENT')),
                ('prnt_date', models.DateField(db_column='PRNT_DATE')),
                ('foc_vendor', models.CharField(db_column='FOC_VENDOR', max_length=1)),
                ('ship_date', models.DateField(db_column='SHIP_DATE')),
                ('srp', models.DecimalField(db_column='SRP', decimal_places=2, max_digits=10)),
                ('category', models.IntegerField(db_column='CATEGORY')),
                ('genre', models.CharField(blank=True, db_column='GENRE', max_length=2, null=True)),
                ('brand_code', models.CharField(blank=True, db_column='BRAND_CODE', max_length=2, null=True)),
                ('mature', models.CharField(db_column='MATURE', max_length=1)),
                ('adult', models.CharField(db_column='ADULT', max_length=1)),
                ('oa', models.CharField(db_column='OA', max_length=1)),
                ('caut1', models.IntegerField(db_column='CAUT1')),
                ('caut2', models.IntegerField(db_column='CAUT2')),
                ('caut3', models.IntegerField(db_column='CAUT3')),
                ('resol', models.CharField(db_column='RESOL', max_length=1)),
                ('note_price', models.CharField(db_column='NOTE_PRICE', max_length=1)),
                ('order_form_notes', models.CharField(blank=True, db_column='ORDER_FORM_NOTES', max_length=255, null=True)),
                ('page', models.IntegerField(db_column='PAGE')),
                ('writer', models.CharField(blank=True, db_column='WRITER', max_length=255, null=True)),
                ('artist', models.CharField(blank=True, db_column='ARTIST', max_length=255, null=True)),
                ('cover_artist', models.CharField(blank=True, db_column='COVER_ARTIST', max_length=255, null=True)),
                ('colorist', models.CharField(blank=True, db_column='COLORIST', max_length=255, null=True)),
                ('alliance_sku', models.CharField(blank=True, db_column='ALLIANCE_SKU', max_length=255, null=True)),
                ('foc_date', models.DateField(blank=True, db_column='FOC_DATE', null=True)),
                ('offered_date', models.DateField(blank=True, db_column='OFFERED_DATE', null=True)),
                ('number_of_pages', models.IntegerField(db_column='NUMBER_OF_PAGES')),
                ('unit_weight', models.DecimalField(db_column='UNIT_WEIGHT', decimal_places=2, max_digits=10)),
                ('unit_length', models.DecimalField(db_column='UNIT_LENGTH', decimal_places=2, max_digits=10)),
                ('unit_width', models.DecimalField(db_column='UNIT_WIDTH', decimal_places=2, max_digits=10)),
                ('unit_height', models.DecimalField(db_column='UNIT_HEIGHT', decimal_places=2, max_digits=10)),
                ('case_weight', models.DecimalField(db_column='CASE_WEIGHT', decimal_places=2, max_digits=10)),
                ('case_length', models.DecimalField(db_column='CASE_LENGTH', decimal_places=1, max_digits=10)),
                ('case_width', models.DecimalField(db_column='CASE_WIDTH', decimal_places=1, max_digits=10)),
                ('case_height', models.DecimalField(db_column='CASE_HEIGHT', decimal_places=1, max_digits=10)),
            ],
            options={
                'db_table': 'processed',
                'managed': False,
            },
        ),
    ]
