# Generated by Django 3.1.3 on 2020-11-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comic',
            table='masterData',
        ),
    ]
