from django.db import models

class Comic(models.Model): # Fields imported from left to right on the original .csv
    diamd_no = models.CharField(max_length=9) # Format: ???######
    stock_no = models.CharField(max_length=9) # Format: STL######
    parent_item_no_alt = models.CharField(max_length=9) # Format: MON######
    bounce_use_item = models.CharField(max_length=9) # Not used in current .csv
    full_title = models.CharField(max_length=60)
    main_desc = models.CharField(max_length=60)
    variant_desc = models.CharField(max_length=60)
    series_code = models.IntegerField()
    issue_no = models.IntegerField()
    issue_seq_no = models.IntegerField()
    volume_tag = models.CharField()
    max_issue = models.IntegerField()
    price = models.DecimalField(decimal_places=2)
    publisher = models.CharField()
    upc_no = models.CharField(max_length=17)
    short_isbn_no = models.CharField(max_length=10)
    ean_no = models.CharField(max_length=18)
    cards_per_pack = models.IntegerField()
    pack_per_box = models.IntegerField()
    box_per_case = models.IntegerField()
    discount_code = models.CharField(max_length=2)
    increment = models.IntegerField()
    prnt_date = models.DateField()
    foc_vendor = models.CharField(max_length=1)
    ship_date = models.DateField()
    srp = models.DecimalField(decimal_places=2)
    category = models.IntegerField()
    genre = models.CharField(max_length=2)
    brand_code = models.CharField(max_length=2)
    mature = models.CharField(max_length=1)
    adult = models.CharField(max_length=1)
    oa = models.CharField(max_length=1)
    caut1 = models.IntegerField()
    caut2 = models.IntegerField()
    caut3 = models.IntegerField()
    resol = models.CharField(max_length=1)
    note_price = models.CharField(max_length=1)
    order_form_notes = models.CharField(max_length=255)
    page = models.IntegerField()
    writer = models.CharField(max_length=255)
    artist = models.CharField(max_length=255)
    cover_artist = models.CharField(max_length=255)
    colorist = models.CharField(max_length=255)
    alliance_sku = models.CharField(max_length=255)
    foc_date = models.DateField()
    offered_date = models.DateField()
    number_of_pages = models.IntegerField()
    unit_weight = models.DecimalField(decimal_places=2)
    unit_length = models.DecimalField(decimal_places=2)
    unit_width = models.DecimalField(decimal_places=2)
    unit_height = models.DecimalField(decimal_places=2)
    case_weight = models.DecimalField(decimal_places=2)
    case_length = models.DecimalField(decimal_places=1)
    case_width = models.DecimalField(decimal_places=1)
    case_height = models.DecimalField(decimal_places=1)
    
